---
service_home: "{{ os_user_home }}/airflow"
airflow_version: "1.6.2"
aws_config_home: "{{ os_user_home }}/.aws"

db_name: "airflow"
db_port: 3306
db_host: "{{ airflow_db_host }}"

services:
- { service_name: "airflow-worker", start_command: "airflow worker", dependencies: "mysql" }
- { service_name: "airflow-scheduler", start_command: "airflow scheduler", dependencies: "mysql airflow-worker" }
- { service_name: "airflow-webserver",  start_command: "airflow webserver",  dependencies: "mysql" }
